#########################################################################
#                                                                       #
#                                  GALAX                                #
#                               XQuery Engine                           #
#                                                                       #
#   Copyright 2001-2007.                                                #
#   Distributed only by permission.                                     #
#                                                                       #
#########################################################################

# Web demo Makefile.config

###########################################################################
# location for a few useful things

# User configuration
# Where is the Galax library (After installation! see ./galax/INSTALL)

# Where to install the demo

WEBSITE=/var/www/html/galax

# where the html documents and javascripts  go

DEMOSITE=$(WEBSITE)/demo

# where the cgi programs to

DEMOCGIBIN=$(WEBSITE)/cgi-bin/

# How the webserver refers to cgi-bin executables. 
# Can let the user specify that directly or,
# use substitutions (which binds us to gmake  - zewei)

#CGIBIN_PREFIX=$(WEBSITE)/cgi-bin/
CGIBIN_PREFIX=http://localhost/galax/cgi-bin/

